name: Blog Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: main
          repository-name: lesonky/lesonky.github.io

      - name: Invoke Cloudflare Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.CLOUDFLARE_WEBHOOK_URL }}
          webhook_secret: "Y0uR5ecr3t"